CREATE TABLE IF NOT EXISTS comments  (
    pk BIGSERIAL PRIMARY KEY,
    id VARCHAR(21) UNIQUE NOT NULL,
    parent_comment_id VARCHAR(21) REFERENCES comments (id) ON DELETE CASCADE NULL,
    post_id VARCHAR(21) NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    comment TEXT NOT NULL,
    images JSONB NULL,
    status VARCHAR(7) NOT NULL,
    level SMALLINT NOT NULL CHECK (level >= 0),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE NULL
  );