CREATE TABLE IF NOT EXISTS public.post_likes (
  pk BIGSERIAL PRIMARY KEY,
  id VARCHAR(21) UNIQUE NOT NULL,
  user_id UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  post_id VARCHAR(21) NOT NULL REFERENCES public.posts (id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

