CREATE TABLE IF NOT EXISTS public.reported_comments (
	pk BIGSERIAL PRIMARY KEY,
  id VARCHAR(21) UNIQUE NOT NULL,
  comment_id VARCHAR(21) UNIQUE NOT NULL REFERENCES comments (id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  reason TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  resolved_at TIMESTAMP WITH TIME ZONE NULL
);
