CREATE TABLE IF NOT EXISTS public.reported_comments (
	pk BIGSERIAL PRIMARY KEY,
  id VARCHAR(21) UNIQUE NOT NULL,
  user_id UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  comment_id VARCHAR(21) REFERENCES comments (id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
