CREATE TABLE IF NOT EXISTS post_history (
	pk BIGSERIAL PRIMARY KEY,
  id VARCHAR(21) UNIQUE NOT NULL,
  post_id VARCHAR(21) NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
 	user_id UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  title VARCHAR(200) NOT NULL,
  cover_image_url TEXT NULL,
  body TEXT NOT NULL,
  images JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
