CREATE TABLE IF NOT EXISTS public.tags (
  pk BIGSERIAL PRIMARY KEY,
  id VARCHAR(21) UNIQUE NOT NULL,
  name character varying NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);